### ISSUE TITLE
Injecting Steamodded causes Steam API to fail on Linux

### ISSUE THREAD

**Issue by korewaChino** [Steamopollys/Steamodded#345]
When injecting Steamodded using Lovely Injector after removing the OS-specific checks so luasteam could be loaded on Linux properly, the Steam API fails to load for some reason

```
[S_API] SteamAPI_Init(): Loaded '/home/cappy/.local/share/Steam/linux64/steamclient.so' OK.
Couldn't connect to steam...
Please ensure that the following conditions are met:
* Do you have Steam turned on?
* If not running from steam, do you have a correct steam_appid.txt file?
* Is the application running under the same user context as steam?
* Is a license for the App ID present in your active steam account?
* Is your App ID correctly set up, i.e. not in ``Release State: Unavailable`` and not missing default packages?
```

Can verify that Steam API connects properly when Steamodded isn't being loaded, with only Lovely Injector and the required patches installed.

# Steps to Reproduce

- Checkout and build <https://github.com/ethangreen-dev/lovely-injector/pull/66>, build Lovely and load it using `LD_PRELOAD=path/to/liblovely.so`
- Now go to `~/.config/love/Mods` and install this Lovely patch to remove the Windows and macOS requirements (Balatro will then attempt to try the macOS method to load `luasteam.so` from the game directory, will be explained later

  ```toml
   [manifest]
   version = "1.2"
   dump_lua = true
   priority = 0
   
   [[patches]]
   [patches.pattern]
   target = "main.lua"
   pattern = '''if os == 'OS X' or os == 'Windows' then'''
   position = "at"
   payload = '''if true then'''
   overwrite = true
   match_indent = true
   
   [[patches]]
   [patches.pattern]
   target = "main.lua"
   pattern = '''if os == 'OS X' then'''
   position = "at"
   payload = '''if true then'''
   overwrite = true
   match_indent = true
   ```

- Download the [Steamworks SDK](https://partner.steamgames.com/doc/sdk) and copy the Steam API libraries to the game directory, specifically copy `steamworks_sdk_161/sdk/redistributable_bin/linux64/libsteam_api.so` to the game directory
- Now, Download the [luasteam](https://github.com/uspgamedev/luasteam) Linux redistributable and copy `linux64_luasteam.so` as `luasteam.so` to the game directory
- Finally, `cd` to the game directory, and run `LD_PRELOAD=liblovely.so love Balatro.exe` or something similar (The LOVE AppImage can be used as well). Personally I use this script to run the game:

  ```sh
  #!/bin/bash
  gamename="Balatro"
  defaultpath="/home/$USER/.local/share/Steam/steamapps/common/$gamename"
  
  LAUNCH_COMMAND="exec love"
  # LAUNCH_COMMAND="$HOME/love-11.5-x86_64.AppImage"
  
  # LD_PRELOAD="libsteam_api.so"
  export LD_PRELOAD="$LD_PRELOAD:liblovely.so"
  export LD_LIBRARY_PATH="$defaultpath"
  pushd "$defaultpath"
  
  $LAUNCH_COMMAND Balatro/ "$@"
  ```

- You should then see that the Steam API loads successfully, and the game now shows in your Steam status

- Now install Steamodded by cloning the repository to `~/.config/love/Mods/Steamodded`, and then run the game again. You should see the error message above

# Expected Behavior

The Steam API should load successfully, and the game should show in your Steam status, Achievements should be unlocked, etc.

# Notes

I can verify that the code in `main.lua` loads `luasteam.so` properly, as it logs to the console, and the loading logic on macOS (which we forced to run using the patch) works as expected. The issue seems to be something with Steamodded itself, modifying some state that causes the Steam API to fail on connection.

```lua
local dir = love.filesystem.getSourceBaseDirectory()
package.cpath = package.cpath .. ';' .. dir .. '/?.so'
local old_cpath = package.cpath
```

Disclosure: I work on an application called [Boson](https://github.com/FyraLabs/boson) which aims to port Windows-only games by running them on their respective native Linux runtimes (Not running the runtime under Wine/Proton but running the underlying framework/engine the game uses by itself, e.g Electron apps on *system Chromium* instead of Chromium in Proton) and I'd be very happy to get this working as it would allow Balatro to run natively on Linux with Steamworks support.
