### ISSUE TITLE
Include a lovely.toml file

### ISSUE THREAD

**Issue by WilsontheWolf** [Steamopollys/Steamodded#39]
It might be a good idea to include a lovely.toml file. The example one on the README of lovely no longer just works for steamodded, as it seems to have added some other stuff, mostly to showcase it's features. Even if it was, it still would need to be updated every time Steamodded get's a new file, etc. which makes more sense to keep updated by steamodded than lovely.
This would also allow people to just clone steamodded into their mod's folder, and it should just work, without having to manually make this file. 

This file should work for the current version of steamodded.
```toml
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.SPEEDFACTOR = 1"
position = "after"
payload = "initSteamodded()"
match_indent = true
overwrite = false

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = [
    "core/core.lua",
    "core/deck.lua",
    "core/joker.lua",
    "core/sprite.lua",
    "core/suit.lua",
    "debug/debug.lua",
    "loader/loader.lua",
]
```
